// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AcceptFriendRequest(arg1:string,arg2:main.HandleFriendRequest):Promise<void>;

export function ApplyFriend(arg1:string,arg2:main.ApplyFriendRequest):Promise<void>;

export function BackendURL():Promise<string>;

export function DeleteFriend(arg1:string,arg2:number):Promise<void>;

export function GetUserInfo(arg1:string):Promise<main.UserResponse>;

export function Greet(arg1:string):Promise<string>;

export function ListFriendRequests(arg1:string):Promise<Array<main.FriendRequestResponse>>;

export function ListFriends(arg1:string):Promise<Array<main.FriendResponse>>;

export function Login(arg1:main.LoginRequest):Promise<main.LoginResponse>;

export function PingBackend():Promise<main.BackendStatus>;

export function Register(arg1:main.RegisterRequest):Promise<main.UserResponse>;

export function RejectFriendRequest(arg1:string,arg2:main.HandleFriendRequest):Promise<void>;

export function SearchUsers(arg1:string,arg2:string):Promise<Array<main.SearchUserResponse>>;

export function SetBackendURL(arg1:string):Promise<string>;

export function UpdateProfile(arg1:string,arg2:main.UpdateProfileRequest):Promise<main.UserResponse>;
