// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriendRequest(arg1, arg2) {
  return window['go']['main']['App']['AcceptFriendRequest'](arg1, arg2);
}

export function ApplyFriend(arg1, arg2) {
  return window['go']['main']['App']['ApplyFriend'](arg1, arg2);
}

export function BackendURL() {
  return window['go']['main']['App']['BackendURL']();
}

export function DeleteFriend(arg1, arg2) {
  return window['go']['main']['App']['DeleteFriend'](arg1, arg2);
}

export function GetUserInfo(arg1) {
  return window['go']['main']['App']['GetUserInfo'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListFriendRequests(arg1) {
  return window['go']['main']['App']['ListFriendRequests'](arg1);
}

export function ListFriends(arg1) {
  return window['go']['main']['App']['ListFriends'](arg1);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function PingBackend() {
  return window['go']['main']['App']['PingBackend']();
}

export function Register(arg1) {
  return window['go']['main']['App']['Register'](arg1);
}

export function RejectFriendRequest(arg1, arg2) {
  return window['go']['main']['App']['RejectFriendRequest'](arg1, arg2);
}

export function SearchUsers(arg1, arg2) {
  return window['go']['main']['App']['SearchUsers'](arg1, arg2);
}

export function SetBackendURL(arg1) {
  return window['go']['main']['App']['SetBackendURL'](arg1);
}

export function UpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfile'](arg1, arg2);
}
